/**
 * TopFlowNG — In-app notification centre.
 *
 * Notifications are generated by real product events (wallet credits,
 * purchase success/pending/failure, scheduled-purchase runs, security events)
 * via `db.createNotification`. This router exposes the customer-facing read/
 * acknowledge surface only; nothing here creates events, so a notification
 * failure can never corrupt a financial transaction.
 */

'use strict';

const { Router } = require('express');
const db = require('../database');
const { authMiddleware } = require('../middleware/auth');
const { apiLimiter } = require('../middleware/rate-limit');
const { sendError } = require('../lib/errors');

const router = Router();

// ── List notifications (paginated, optional category filter) ────────────────
router.get('/', authMiddleware, apiLimiter, async (req, res) => {
  try {
    const limit = Math.min(parseInt(req.query.limit) || 30, 100);
    const offset = Math.max(parseInt(req.query.offset) || 0, 0);
    const category = String(req.query.category || 'all').slice(0, 20);
    const unreadOnly = req.query.unread === '1' || req.query.unread === 'true';
    const result = await db.getNotifications(req.user.id, { limit, offset, category, unreadOnly });
    res.json(result);
  } catch (err) {
    sendError(res, 500, 'Failed to load notifications');
  }
});

// ── Unread count (for the bell badge) ────────────────────────────────────────
router.get('/unread-count', authMiddleware, apiLimiter, async (req, res) => {
  try {
    const unread = await db.getUnreadNotificationCount(req.user.id);
    res.json({ unread });
  } catch (err) {
    sendError(res, 500, 'Failed to load notification count');
  }
});

// ── Mark a single notification read ──────────────────────────────────────────
router.post('/read/:id', authMiddleware, apiLimiter, async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isInteger(id) || id < 1) return sendError(res, 400, 'Invalid notification');
    const updated = await db.markNotificationRead(req.user.id, id);
    res.json({ ok: true, read: !!updated });
  } catch (err) {
    sendError(res, 500, 'Failed to update notification');
  }
});

// ── Mark all notifications read ──────────────────────────────────────────────
router.post('/read-all', authMiddleware, apiLimiter, async (req, res) => {
  try {
    const count = await db.markAllNotificationsRead(req.user.id);
    res.json({ ok: true, marked: count });
  } catch (err) {
    sendError(res, 500, 'Failed to update notifications');
  }
});

// ── Delete a single notification ─────────────────────────────────────────────
router.delete('/:id', authMiddleware, apiLimiter, async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isInteger(id) || id < 1) return sendError(res, 400, 'Invalid notification');
    const deleted = await db.deleteNotification(req.user.id, id);
    res.json({ ok: true, deleted: !!deleted });
  } catch (err) {
    sendError(res, 500, 'Failed to delete notification');
  }
});

module.exports = router;